version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos_laravel_app
    ports:
      - "8082:80"
    volumes:
      - ../:/var/www/html 
    networks:
      - pos_laravel

  db:
    image: mysql:latest
    ports:
      - "3308:3306"
    container_name: pos_laravel_db
    environment:
      MYSQL_DATABASE: pos_laravel
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata_pos:/var/lib/mysql
    networks:
      - pos_laravel

networks:
  pos_laravel:
    driver: bridge

volumes:
  dbdata_pos:


